<a href="https://colab.research.google.com/github/aayushgadhiya128830-ship-it/92400527237_Aayush_Gadhiya_BCA_6D__Machine_Learing__Marwadi_University/blob/main/P4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/01 covid_toy (1).csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
print(df.cough.value_counts())

print()
print()

print(df.city.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64


city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

age - numeric column
gender - Nominal categorical column(One-Hot encoding)
fever - Numeric column. Has missing values. Will apply simple imputer to fill missing values
cough - Ordinal categorical column(Ordinal encoding)
city - Nominal categorical column(One-Hot encoding)
has_covid - Target column categorical.(Label encoding)

Here, we will work with columns gender, fever, cough and city as discussed above .

In [ ]:
x = df.iloc[:,0:5]
y = df.drop(x, axis = 'columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age  gender  fever   cough     city
4    65  Female  101.0    Mild   Mumbai
94   79    Male    NaN  Strong  Kolkata
82   24    Male   98.0    Mild  Kolkata
0    60    Male  103.0    Mild  Kolkata
70   68  Female  101.0  Strong    Delhi


   has_covid
4         No
94       Yes
82       Yes
0         No
70        No

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [ ]:
si = SimpleImputer()
le = LabelEncoder()

In [10]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.fit_transform(y_test['has_covid'])

In [11]:
x_train['fever'] = si.fit_transform(x_train[['fever']])

In [17]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False)

In [15]:
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [16]:
x_train

    age  gender       fever   cough       city
4    65  Female  101.000000    Mild     Mumbai
94   79    Male  100.722222  Strong    Kolkata
82   24    Male   98.000000    Mild    Kolkata
0    60    Male  103.000000    Mild    Kolkata
70   68  Female  101.000000  Strong      Delhi
..  ...     ...         ...     ...        ...
56   71    Male  100.722222  Strong    Kolkata
32   34  Female  101.000000  Strong      Delhi
96   51  Female  101.000000  Strong    Kolkata
25   23    Male  100.722222    Mild     Mumbai
48   66    Male   99.000000  Strong  Bangalore

[80 rows x 5 columns]

In [18]:
transformer = [('trans1',SimpleImputer(),['fever']),
               ('trans2',OrdinalEncoder(categories = [['Mild','Strong']]),['cough']),
               ('trans3',OneHotEncoder(sparse_output = False,drop = 'first'),['gender','city'])]

In [21]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = transformer,remainder = 'passthrough').set_output(transform = 'pandas')

In [23]:
x_train_transformed = ct.fit_transform(x_train)

In [24]:
x_train_trans = ct.fit_transform(x_train)

In [25]:
x_train_trans.sample(5)

,trans1__fever,trans2__cough,trans3__gender_Male,trans3__city_Delhi,trans3__city_Kolkata,trans3__city_Mumbai,remainder__age
10,100.722222,0.0,0.0,1.0,0.0,0.0,75
1,100.000000,0.0,1.0,1.0,0.0,0.0,27
77,101.000000,0.0,0.0,0.0,1.0,0.0,8
96,101.000000,1.0,0.0,0.0,1.0,0.0,51
22,98.000000,1.0,0.0,0.0,1.0,0.0,71

In [26]:
x_test_trans = ct.transform(x_test)

In [28]:
x_train_trans.shape

(80, 7)

In [27]:
print(x_train_trans.sample(5))
print()
print()
print(x_test_trans.shape)

    trans1__fever  trans2__cough  trans3__gender_Male  trans3__city_Delhi  \
68          104.0            1.0                  0.0                 0.0
28          104.0            0.0                  1.0                 0.0
13          102.0            0.0                  1.0                 0.0
27          102.0            1.0                  0.0                 1.0
2           101.0            0.0                  1.0                 1.0

    trans3__city_Kolkata  trans3__city_Mumbai  remainder__age
68                   1.0                  0.0              54
28                   1.0                  0.0              16
13                   0.0                  0.0              64
27                   0.0                  0.0              33
2                    0.0                  0.0              42


(20, 7)